//
//  main.cpp
//  #2: Even Fibonacci numbers
/*
 Even Fibonacci numbers
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
//  Created by Jungjae Lee on 4/30/13.
//  Copyright (c) 2013 Jungjae Lee. All rights reserved.
//

#include <iostream>

int main(int argc, const char * argv[])
{
    int number1 = 1;
    int number2 = 2;
    int number3 = number1 + number2;
    int sum = number2;
    
    while (number3<=4000000) {
        if(number3%2==0) {
            sum += number3;
        }
        
        number3 = number1 + number2;
        
        if (number1 < number2) {
            number1 = number3;
        }else {
            number2 = number3;
        }
    }
    
    std::cout << sum << std::endl;
    return 0;
}

